#!/usr/bin/env bash
set -Eeuo pipefail

psql --set ON_ERROR_STOP=on --username "$POSTGRES_USER" <<-SQL
  CREATE USER ${OPENWEBUI_DB_USER} WITH PASSWORD '${OPENWEBUI_DB_PASSWORD}';
  CREATE DATABASE ${OPENWEBUI_DB_NAME} OWNER ${OPENWEBUI_DB_USER};

  CREATE USER ${AUTHENTIK_DB_USER} WITH PASSWORD '${AUTHENTIK_DB_PASSWORD}';
  CREATE DATABASE ${AUTHENTIK_DB_NAME} OWNER ${AUTHENTIK_DB_USER};

  CREATE USER ${MEM0_DB_USER} WITH PASSWORD '${MEM0_DB_PASSWORD}';
  CREATE DATABASE ${MEM0_DB_NAME} OWNER ${MEM0_DB_USER};
  \connect ${MEM0_DB_NAME}
  CREATE EXTENSION IF NOT EXISTS vector;
SQL
